### PR TITLE
add mixed-mode test files

### PR DESCRIPTION
**Pull request by williballenthin**

### CODE REVIEW

**Comment by malwarefrank** [comment]
😱

**Comment by malwarefrank** [comment]
can you add source from which the executables can be replicated

**Comment by williballenthin** [comment]
I will ask. I can probably share the source files, not sure on the build config. (I didn’t create these samples so need to check with the author). 

To be honest, we’re a little concerned that our tools don’t handle these files well today so my organization may want to avoid proliferation until that improves.

**Comment by williballenthin** [comment]
source files added. I can share the build files privately if you'd like them.

@tarterp is also working to further refine the build process and artifacts to capture more cases.

**Pull request merged**
